import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const bathBodyImages = [
  'https://images.unsplash.com/photo-1556228578-0d85751bab9b?w=800&q=80',
  'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=800&q=80',
  'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=800&q=80',
  'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=800&q=80',
  'https://images.unsplash.com/photo-1585232350386-0b3c8674f56e?w=800&q=80',
]

const skincareImages = [
  'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800&q=80',
  'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800&q=80',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80',
  'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80',
  'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80',
]

const homeImages = [
  'https://images.unsplash.com/photo-1603006905003-be319992b18b?w=800&q=80',
  'https://images.unsplash.com/photo-1602874801007-bd458bb1b8b2?w=800&q=80',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
  'https://images.unsplash.com/photo-1545239705-1564e58b9e4c?w=800&q=80',
  'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80',
]

const bb = (i: number) => bathBodyImages[i % bathBodyImages.length]
const sk = (i: number) => skincareImages[i % skincareImages.length]
const hf = (i: number) => homeImages[i % homeImages.length]

const products = [
  // BATH & BODY (25)
  {
    name: 'Ritual of Sakura Body Wash',
    slug: 'ritual-of-sakura-body-wash',
    shortDescription: 'Blooming cherry blossom & rice milk foam cleanser',
    description: 'Surrender to the ancient Japanese ritual of renewal. This luxuriant foaming body wash, enriched with the delicate essence of cherry blossom and the nourishing purity of rice milk, transforms your daily cleanse into a meditative ceremony. The skin is left luminously soft, veiled in a whisper of spring petals.',
    price: 1890,
    category: 'bath-body',
    subcategory: 'body-wash',
    imageUrl: bb(0),
    images: [bb(0), bb(1)],
    ingredients: 'Aqua, Sodium Laureth Sulfate (derived from coconut), Cherry Blossom Extract (Prunus serrulata), Rice Milk Protein, Glycerin (plant-derived), Panthenol (Vitamin B5), Fragrance (natural), Citric Acid',
    sustainabilityInfo: 'Bottle made from 100% recycled ocean plastic. Formula is 85% natural origin. Biodegradable formula. Cruelty-free & vegan.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Ancient Oud Body Scrub',
    slug: 'ancient-oud-body-scrub',
    shortDescription: 'Oud wood & brown sugar exfoliating ritual',
    description: 'Drawn from the ancient spice routes of Arabia, this opulent body scrub merges the smoky depth of oud wood with the gentle abrasion of raw brown sugar crystals. Each application is a sensory pilgrimage — polishing away the ordinary to reveal skin reborn in warmth and mystery.',
    price: 2290,
    category: 'bath-body',
    subcategory: 'scrubs',
    imageUrl: bb(1),
    images: [bb(1), bb(2)],
    ingredients: 'Brown Sugar, Coconut Oil (Cocos nucifera), Oud Wood Extract (Aquilaria agallocha), Sweet Almond Oil, Vitamin E (Tocopherol), Shea Butter, Natural Fragrance',
    sustainabilityInfo: 'Packaging made from FSC-certified recycled cardboard. 90% natural ingredients. Palm oil-free. Vegan & cruelty-free.',
    isBestseller: false,
    isNew: true,
  },
  {
    name: 'White Lotus Body Lotion',
    slug: 'white-lotus-body-lotion',
    shortDescription: 'Sacred white lotus & jasmine whipped moisturiser',
    description: 'Inspired by the sacred lotus that blooms in still water, this silken lotion glides onto skin like a second dawn. White lotus extract, revered for centuries in Ayurvedic tradition, merges with jasmine absolute to restore supple luminosity. A moment of pure, unhurried devotion.',
    price: 1690,
    category: 'bath-body',
    subcategory: 'lotions',
    imageUrl: bb(2),
    images: [bb(2), bb(3)],
    ingredients: 'Aqua, White Lotus Extract (Nelumbo nucifera), Jasmine Absolute, Shea Butter, Glycerin, Jojoba Oil, Niacinamide, Hyaluronic Acid, Natural Fragrance',
    sustainabilityInfo: '100% recyclable glass bottle with bamboo pump. 88% natural origin. Reef-safe formula. Certified vegan.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Rose & Sandalwood Bath Oil',
    slug: 'rose-sandalwood-bath-oil',
    shortDescription: 'Damask rose & Mysore sandalwood immersion oil',
    description: 'A bath oil worthy of maharanis. Rare Damask rose petals distilled over moonlit nights meet the creamy warmth of Mysore sandalwood in this transformative elixir. Dissolve it into warm water and surrender — the skin emerges wrapped in velvet, the mind stilled to a quiet reverence.',
    price: 2890,
    category: 'bath-body',
    subcategory: 'bath-oils',
    imageUrl: bb(3),
    images: [bb(3), bb(4)],
    ingredients: 'Prunus Amygdalus Dulcis (Sweet Almond) Oil, Rosa Damascena (Damask Rose) Extract, Santalum Album (Sandalwood) Oil, Jojoba Oil, Vitamin E, Rose Absolute, Natural Fragrance',
    sustainabilityInfo: 'Sustainably sourced sandalwood from certified Karnataka farms. Refillable glass bottle. 95% natural origin. Zero synthetic preservatives.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Ritual of Hammam Scrub',
    slug: 'ritual-of-hammam-scrub',
    shortDescription: 'Black soap & eucalyptus deep cleansing kessa scrub',
    description: 'Channel the centuries-old Moroccan hammam tradition. Authentic black soap — crafted from olive oil and crushed olives — softens and opens the skin, while eucalyptus essential oil purifies and awakens. Massage in slow, deliberate circles: this is not a hurried act, but a sacred weekly offering to yourself.',
    price: 2190,
    category: 'bath-body',
    subcategory: 'scrubs',
    imageUrl: bb(4),
    images: [bb(4), bb(0)],
    ingredients: 'Olea europaea (Olive) Fruit Oil, Black Soap, Eucalyptus Globulus Leaf Oil, Argan Oil, Sea Salt, Glycerin, Vitamin E, Natural Fragrance',
    sustainabilityInfo: 'Fair-trade olive oil sourced from Moroccan cooperatives. Packaging: 100% recycled aluminium. Vegan & cruelty-free.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Jasmine Hand Wash',
    slug: 'jasmine-hand-wash',
    shortDescription: 'Night-blooming jasmine foaming hand cleanser',
    description: 'The jasmine blooms only after dusk — and its essence, captured at the peak of its nocturnal unfurling, infuses every drop of this gentle hand wash. Skin is cleansed without compromise, left soft as the first hour of evening.',
    price: 890,
    category: 'bath-body',
    subcategory: 'hand-care',
    imageUrl: bb(0),
    images: [bb(0), bb(1)],
    ingredients: 'Aqua, Sodium Coco-Sulfate, Jasmine Sambac Extract, Glycerin, Aloe Vera, Chamomile Extract, Citric Acid, Natural Fragrance',
    sustainabilityInfo: 'Refillable format available. 100% plastic-neutral packaging. Biodegradable formula. Vegan & cruelty-free.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Vetiver & Cedar Hand Cream',
    slug: 'vetiver-cedar-hand-cream',
    shortDescription: 'Earthy vetiver & cedarwood intensive hand treatment',
    description: 'Vetiver, the fragrant root known as liquid gold in India, meets the grounding warmth of Atlas cedarwood in this intensive hand cream. Deeply nourishing, it repairs and protects hands weathered by the elements — a quiet, earthly ceremony for those who work with their hands.',
    price: 990,
    category: 'bath-body',
    subcategory: 'hand-care',
    imageUrl: bb(1),
    images: [bb(1), bb(2)],
    ingredients: 'Aqua, Shea Butter, Vetiver Root Extract, Cedarwood Oil, Glycerin, Beeswax (ethically sourced), Vitamin E, Allantoin, Natural Fragrance',
    sustainabilityInfo: 'Vetiver sourced from regenerative farms in Rajasthan. Sugarcane-derived packaging. 92% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Moonflower Body Butter',
    slug: 'moonflower-body-butter',
    shortDescription: 'Whipped moonflower & mango butter overnight treatment',
    description: 'As the world surrenders to sleep, let your skin begin its most sacred work. This cloud-like whipped butter, crafted from moonflower extract and rich mango seed butter, melts on contact — sinking deep into the dermis to restore, replenish and renew through every sleeping hour.',
    price: 1990,
    category: 'bath-body',
    subcategory: 'lotions',
    imageUrl: bb(2),
    images: [bb(2), bb(3)],
    ingredients: 'Mangifera Indica (Mango) Seed Butter, Moonflower Extract (Ipomoea alba), Shea Butter, Coconut Oil, Vitamin E, Argan Oil, Lavender Essential Oil, Natural Fragrance',
    sustainabilityInfo: 'Mango butter sourced from Alphonso mango cooperatives in Maharashtra. Glass jar, 100% recyclable. Vegan & cruelty-free.',
    isBestseller: false,
    isNew: true,
  },
  {
    name: 'Sea Salt & Coconut Exfoliant',
    slug: 'sea-salt-coconut-exfoliant',
    shortDescription: 'Himalayan sea salt & virgin coconut polishing scrub',
    description: 'Drawn from the ancient Himalayan sea beds and the tropical abundance of Kerala\'s coconut groves, this polishing scrub is the simplest luxury. Salt crystals dissolve as they work, releasing minerals while coconut oil seals each newly revealed layer of skin in pure, sweet moisture.',
    price: 1790,
    category: 'bath-body',
    subcategory: 'scrubs',
    imageUrl: bb(3),
    images: [bb(3), bb(4)],
    ingredients: 'Himalayan Salt, Cocos Nucifera (Coconut) Oil, Coconut Sugar, Lime Essential Oil, Vitamin E, Glycerin, Natural Fragrance',
    sustainabilityInfo: 'Himalayan salt hand-mined with zero mechanical extraction. Coconut oil from certified sustainable Kerala farms. 98% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Saffron & Honey Bath Soak',
    slug: 'saffron-honey-bath-soak',
    shortDescription: 'Kashmiri saffron & raw forest honey bath ritual',
    description: 'Saffron — more precious than gold, cultivated in the high meadows of Kashmir — is dissolved into this amber bath soak alongside the raw wildflower honey of the Himalayan forests. Step into this golden bath and feel centuries of beauty wisdom envelop you completely.',
    price: 2490,
    category: 'bath-body',
    subcategory: 'bath-soaks',
    imageUrl: bb(4),
    images: [bb(4), bb(0)],
    ingredients: 'Dead Sea Salt, Kashmiri Saffron (Crocus sativus), Raw Himalayan Forest Honey, Milk Protein, Rose Extract, Calendula, Vitamin E, Natural Fragrance',
    sustainabilityInfo: 'Saffron sourced directly from Kashmir cooperative farms at fair-trade premium. 96% natural origin. Fully biodegradable formula.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Patchouli Shower Oil',
    slug: 'patchouli-shower-oil',
    shortDescription: 'Deep patchouli & ylang ylang sensory shower oil',
    description: 'A rare alchemy: an oil that transforms into a silken lather upon contact with water. Patchouli — dark, earthy, hypnotic — is balanced by the sweetly floral ylang ylang, creating a sensory encounter that lingers long after you step out into the world.',
    price: 1590,
    category: 'bath-body',
    subcategory: 'body-wash',
    imageUrl: bb(0),
    images: [bb(0), bb(1)],
    ingredients: 'Sunflower Oil, Patchouli Essential Oil, Ylang Ylang Essential Oil, Jojoba Oil, Vitamin E, Polysorbate 80 (plant-derived), Natural Fragrance',
    sustainabilityInfo: 'Cold-pressed sunflower oil from certified EU sustainable farms. 100% natural fragrance. Vegan & cruelty-free.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Lavender Dream Body Mist',
    slug: 'lavender-dream-body-mist',
    shortDescription: 'Provence lavender & bergamot calming body mist',
    description: 'Misted across sun-warmed skin, this weightless veil of Provençal lavender and bergamot is an invitation to slow down. The most ephemeral luxury — a breath, a cloud, a moment held still before it dissolves into the afternoon.',
    price: 1290,
    category: 'bath-body',
    subcategory: 'body-mists',
    imageUrl: bb(1),
    images: [bb(1), bb(2)],
    ingredients: 'Aqua, Alcohol (sugarcane-derived), Lavandula Angustifolia (Lavender) Oil, Bergamot Essential Oil, Aloe Vera, Glycerin, Natural Fragrance',
    sustainabilityInfo: 'Sugarcane-derived alcohol — carbon-negative production. Recycled aluminium spray bottle. 90% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Ritual of Namaste Body Balm',
    slug: 'ritual-of-namaste-body-balm',
    shortDescription: 'Indian rose & holy basil restorative body balm',
    description: 'Namaste — I honour the divine within you. This restorative balm, born of the ancient meeting between Indian rose and holy basil (tulsi), asks you to honour the temple of your own body. Smooth it slowly into every curve, every grace note of your form.',
    price: 1890,
    category: 'bath-body',
    subcategory: 'lotions',
    imageUrl: bb(2),
    images: [bb(2), bb(3)],
    ingredients: 'Shea Butter, Indian Rose Extract (Rosa indica), Tulsi (Holy Basil) Extract, Coconut Oil, Vitamin E, Turmeric Extract, Sandalwood Oil, Natural Fragrance',
    sustainabilityInfo: 'Tulsi sourced from biodynamic Indian farms. Refillable tin packaging. 93% natural origin. Vegan & cruelty-free.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Amber & Vanilla Body Wash',
    slug: 'amber-vanilla-body-wash',
    shortDescription: 'Warm amber resin & Madagascar vanilla cleansing gel',
    description: 'Amber — fossilised light, ancient warmth — meets the creamy sweetness of Madagascar vanilla in this enveloping body wash. It is comfort made liquid, nostalgia transformed into lather: the scent of a memory you cannot quite place but never wish to forget.',
    price: 1690,
    category: 'bath-body',
    subcategory: 'body-wash',
    imageUrl: bb(3),
    images: [bb(3), bb(4)],
    ingredients: 'Aqua, Sodium Laureth Sulfate, Amber Resin Extract, Vanilla planifolia Extract, Glycerin, Coconut Oil, Shea Butter, Panthenol, Natural Fragrance',
    sustainabilityInfo: '100% recycled plastic bottle. Biodegradable formula. Natural vanilla from certified Madagascar cooperative. Vegan.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Neroli Blossom Hand Wash',
    slug: 'neroli-blossom-hand-wash',
    shortDescription: 'Sicilian neroli & orange blossom foaming wash',
    description: 'Neroli — the blossom of the bitter orange, coaxed into oil through painstaking steam distillation — has adorned the hands of nobility for five centuries. Its bright, honeyed citrus lifts the spirit as it cleanses, leaving hands impossibly soft and faintly luminous.',
    price: 890,
    category: 'bath-body',
    subcategory: 'hand-care',
    imageUrl: bb(4),
    images: [bb(4), bb(0)],
    ingredients: 'Aqua, Sodium Coco-Sulfate, Neroli Essential Oil (Citrus aurantium), Orange Blossom Water, Glycerin, Aloe Vera, Vitamin B5, Natural Fragrance',
    sustainabilityInfo: 'Neroli from certified Sicilian organic groves. Refillable format available. Biodegradable. Vegan & cruelty-free.',
    isBestseller: false,
    isNew: true,
  },
  {
    name: 'Charcoal Detox Body Scrub',
    slug: 'charcoal-detox-body-scrub',
    shortDescription: 'Activated bamboo charcoal & mint deep detox scrub',
    description: 'Like a forest rain after the dry season, this detoxifying scrub draws out impurities with the magnetic pull of activated bamboo charcoal, while peppermint sends a cooling current across the skin. What remains is a body that breathes freely — clarified, alive, renewed.',
    price: 2090,
    category: 'bath-body',
    subcategory: 'scrubs',
    imageUrl: bb(0),
    images: [bb(0), bb(1)],
    ingredients: 'Activated Bamboo Charcoal, Sea Salt, Coconut Oil, Peppermint Essential Oil, Kaolin Clay, Tea Tree Oil, Glycerin, Vitamin E',
    sustainabilityInfo: 'Bamboo charcoal from sustainably managed Japanese bamboo forests. 100% natural ingredients. Compostable packaging.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Gold & Tuberose Body Lotion',
    slug: 'gold-tuberose-body-lotion',
    shortDescription: '24K gold flakes & tuberose absolute luminising lotion',
    description: 'There is a reason tuberose is called the most seductive flower in the world — its heavy, creamy sweetness is intoxicating in the most civilised way. Suspended in this luminising lotion alongside 24K gold flakes, it transforms your skin into something that catches light, that holds attention, that lingers.',
    price: 1990,
    category: 'bath-body',
    subcategory: 'lotions',
    imageUrl: bb(1),
    images: [bb(1), bb(2)],
    ingredients: '24K Gold Flakes, Tuberose Absolute (Polianthes tuberosa), Hyaluronic Acid, Shea Butter, Glycerin, Jojoba Oil, Mica, Vitamin E, Natural Fragrance',
    sustainabilityInfo: 'Ethically sourced 24K gold. Refillable glass bottle with gold pump. 87% natural origin.',
    isBestseller: false,
    isNew: true,
  },
  {
    name: 'Ritual of Ayurveda Bath Salts',
    slug: 'ritual-of-ayurveda-bath-salts',
    shortDescription: 'Triphala & neem Ayurvedic mineral bath salts',
    description: 'Five thousand years of wisdom distilled into a single bath. These mineral-rich salts, blended with the legendary Ayurvedic trinity of triphala and purifying neem, draw the body into balance — the ancient science of doshas made tangible in the warmth of your evening bath.',
    price: 1490,
    category: 'bath-body',
    subcategory: 'bath-soaks',
    imageUrl: bb(2),
    images: [bb(2), bb(3)],
    ingredients: 'Himalayan Pink Salt, Dead Sea Salt, Triphala Extract (Amla, Haritaki, Bibhitaki), Neem Extract, Turmeric, Ashwagandha, Vetiver Oil, Natural Fragrance',
    sustainabilityInfo: 'Triphala from certified Ayurvedic farms in Madhya Pradesh. Compostable kraft packaging. 97% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Midnight Jasmine Shower Gel',
    slug: 'midnight-jasmine-shower-gel',
    shortDescription: 'Sambac jasmine & black orchid after-dark shower gel',
    description: 'Jasmine waits until midnight to reveal its deepest self. This shower gel, crafted with sambac jasmine harvested in the blue hour before dawn, captures that fleeting nocturnal intensity — paired with the rare black orchid, it transforms the shower into something altogether more mysterious.',
    price: 1390,
    category: 'bath-body',
    subcategory: 'body-wash',
    imageUrl: bb(3),
    images: [bb(3), bb(4)],
    ingredients: 'Aqua, Sodium Laureth Sulfate, Jasmine Sambac Extract, Black Orchid Extract, Glycerin, Panthenol, Coconut Betaine, Natural Fragrance',
    sustainabilityInfo: 'Jasmine from night-harvest cooperative in Tamil Nadu. 100% recycled packaging. Biodegradable. Vegan.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Rose Hip Body Oil',
    slug: 'rose-hip-body-oil',
    shortDescription: 'Chilean rosehip & marula regenerating dry body oil',
    description: 'Cold-pressed from the seed of the wild Chilean rose, rosehip oil carries within it an extraordinary concentration of Vitamin A and essential fatty acids — nature\'s most potent regenerating gift. Paired with rare marula oil from Southern Africa, this dry body oil absorbs instantly, leaving only a luminous, satin finish.',
    price: 2690,
    category: 'bath-body',
    subcategory: 'body-oils',
    imageUrl: bb(4),
    images: [bb(4), bb(0)],
    ingredients: 'Rosa Canina (Rosehip) Seed Oil, Sclerocarya birrea (Marula) Oil, Jojoba Oil, Sea Buckthorn Extract, Vitamin E, Lavender Essential Oil, Natural Fragrance',
    sustainabilityInfo: 'Rosehip cold-pressed in Chile from wild-harvested berries. Marula from fair-trade South African women\'s cooperative. 100% natural origin.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Coconut & Cardamom Body Wash',
    slug: 'coconut-cardamom-body-wash',
    shortDescription: 'Kerala coconut milk & green cardamom spiced wash',
    description: 'Kerala — God\'s Own Country — has always known the secret of the coconut. Here, its pure milk is spiced with freshly crushed green cardamom: warm, aromatic, faintly sweet. A morning wash that awakens the senses as gently and completely as a first sip of chai.',
    price: 1590,
    category: 'bath-body',
    subcategory: 'body-wash',
    imageUrl: bb(0),
    images: [bb(0), bb(1)],
    ingredients: 'Aqua, Coconut Milk (Cocos nucifera), Cardamom Essential Oil, Sodium Coco-Sulfate, Glycerin, Shea Butter, Aloe Vera, Natural Fragrance',
    sustainabilityInfo: 'Coconut from certified organic Kerala farms. Cardamom from fair-trade Idukki cooperative. 91% natural origin. Vegan.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Silk & Pearl Hand Lotion',
    slug: 'silk-pearl-hand-lotion',
    shortDescription: 'Marine pearl extract & silk protein brightening hand lotion',
    description: 'Pearl powder has adorned the complexions of empresses for millennia. Here, its luminising essence is suspended in a featherweight lotion alongside silk amino acids that bind moisture to skin at a molecular level. Your hands, touched daily by the world, deserve this quiet extravagance.',
    price: 1190,
    category: 'bath-body',
    subcategory: 'hand-care',
    imageUrl: bb(1),
    images: [bb(1), bb(2)],
    ingredients: 'Aqua, Pearl Powder, Silk Amino Acids, Glycerin, Shea Butter, Niacinamide, Hyaluronic Acid, Vitamin C (Ascorbyl Glucoside), Natural Fragrance',
    sustainabilityInfo: 'Pearl extract ethically sourced from freshwater pearl farms. Sugarcane-derived tube. 88% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Ritual of Rebirth Body Scrub',
    slug: 'ritual-of-rebirth-body-scrub',
    shortDescription: 'Volcanic pumice & green tea renewal body scrub',
    description: 'From volcanic earth, rebirth. Fine pumice — formed in the fires of ancient volcanoes — polishes the skin with a precision no synthetic bead can replicate, while green tea floods the freshly revealed surface with antioxidant vitality. This is transformation as ritual, renewal as ceremony.',
    price: 2390,
    category: 'bath-body',
    subcategory: 'scrubs',
    imageUrl: bb(2),
    images: [bb(2), bb(3)],
    ingredients: 'Volcanic Pumice, Green Tea Extract (Camellia sinensis), Coconut Oil, Sea Salt, Matcha Powder, Vitamin E, Peppermint Oil, Natural Fragrance',
    sustainabilityInfo: 'Volcanic pumice from sustainably mined Icelandic sources. Compostable bamboo packaging. 96% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Argan & Rose Body Elixir',
    slug: 'argan-rose-body-elixir',
    shortDescription: 'Liquid gold argan & Bulgarian rose prestige body serum',
    description: 'The rarest meeting: liquid gold argan oil from the ancient forests of Morocco\'s Anti-Atlas mountains, and Bulgarian rose — queen of flowers, requiring six tonnes of petals to yield a single kilogram of absolute. This prestige body elixir is the ultimate act of self-reverence.',
    price: 3190,
    category: 'bath-body',
    subcategory: 'body-oils',
    imageUrl: bb(3),
    images: [bb(3), bb(4)],
    ingredients: 'Argania Spinosa (Argan) Kernel Oil, Rosa Damascena (Bulgarian Rose) Absolute, Marula Oil, Vitamin E, Sea Buckthorn Extract, Neroli Oil, Natural Fragrance',
    sustainabilityInfo: 'Argan oil from women\'s co-operative in Essaouira, Morocco — certified fair trade. Rose absolute from certified Bulgarian organic farms. 100% natural origin.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Himalayan Salt Body Polish',
    slug: 'himalayan-salt-body-polish',
    shortDescription: 'Pink Himalayan salt & orange blossom mineral polish',
    description: 'Formed over 250 million years beneath ancient seabeds and elevated into mountains, Himalayan pink salt carries within its crystalline structure a mineral complexity that synthetic scrubs cannot approach. Dissolved in orange blossom water and sweet almond oil, it polishes the skin to a mineral-rich radiance.',
    price: 2190,
    category: 'bath-body',
    subcategory: 'scrubs',
    imageUrl: bb(4),
    images: [bb(4), bb(0)],
    ingredients: 'Himalayan Pink Salt, Sweet Almond Oil, Orange Blossom Water, Coconut Oil, Vitamin E, Calendula Extract, Orange Essential Oil, Natural Fragrance',
    sustainabilityInfo: 'Salt hand-mined using traditional methods in Khewra, Pakistan. 99% natural origin. Recyclable glass jar.',
    isBestseller: false,
    isNew: false,
  },

  // SKINCARE (20)
  {
    name: 'White Lotus Cleansing Oil',
    slug: 'white-lotus-cleansing-oil',
    shortDescription: 'Sacred white lotus & jojoba melting cleansing oil',
    description: 'The first step of every ritual is the clearing. This melting cleansing oil — infused with sacred white lotus and pure jojoba — dissolves makeup, sunscreen and the day\'s invisible accumulations without disturbing the skin\'s sacred equilibrium. Emulsify with water and it rinses clean, leaving the skin balanced and prepared for what follows.',
    price: 2490,
    category: 'skincare',
    subcategory: 'cleansers',
    imageUrl: sk(0),
    images: [sk(0), sk(1)],
    ingredients: 'Jojoba Oil, White Lotus Extract, Sunflower Oil, Vitamin E, Polysorbate 80 (plant-derived), Rose Hip Oil, Chamomile Extract, Natural Fragrance',
    sustainabilityInfo: 'White lotus extract from certified organic farms. Refillable glass bottle. 97% natural origin. Vegan & cruelty-free.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Sakura Brightening Serum',
    slug: 'sakura-brightening-serum',
    shortDescription: 'Cherry blossom & Vitamin C radiance-boosting serum',
    description: 'In Japan, the sakura is not merely a flower — it is a philosophy: the beauty of impermanence, the discipline of presence. This brightening serum, concentrated with cherry blossom ferment and stabilised Vitamin C, invites your skin into that same luminous transience — radiant today, more radiant tomorrow.',
    price: 3890,
    category: 'skincare',
    subcategory: 'serums',
    imageUrl: sk(1),
    images: [sk(1), sk(2)],
    ingredients: 'Aqua, Fermented Cherry Blossom Extract, Ascorbyl Glucoside (Vitamin C), Niacinamide, Hyaluronic Acid, Alpha Arbutin, Tranexamic Acid, Glycerin, Natural Fragrance',
    sustainabilityInfo: 'Fermentation process reduces CO2 by 40% vs conventional extraction. Refillable glass dropper. 82% natural origin.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Ancient Gold Face Cream',
    slug: 'ancient-gold-face-cream',
    shortDescription: '24K gold & saffron royal anti-aging face cream',
    description: 'Gold has adorned the faces of pharaohs, maharajas and empresses throughout human history — not merely for its beauty, but for its extraordinary ability to stimulate and illuminate the skin. In this opulent face cream, 24K gold meets Kashmiri saffron and a wealth of actives in the most regal daily ritual.',
    price: 4290,
    category: 'skincare',
    subcategory: 'moisturisers',
    imageUrl: sk(2),
    images: [sk(2), sk(3)],
    ingredients: '24K Gold, Kashmiri Saffron Extract, Retinol Alternative (Bakuchiol), Hyaluronic Acid, Peptide Complex, Shea Butter, Vitamin E, Niacinamide, Natural Fragrance',
    sustainabilityInfo: 'Ethically sourced 24K gold. Saffron from Kashmir cooperative. Refillable luxury glass jar. 85% natural origin.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Ritual of Namaste Eye Cream',
    slug: 'ritual-of-namaste-eye-cream',
    shortDescription: 'Caffeine & Indian ginseng brightening eye treatment',
    description: 'The eyes speak before words do. This lightweight eye cream, charged with the awakening energy of caffeine and the ancient vitality of Indian ginseng (ashwagandha), addresses dark circles, puffiness and fine lines with the precision of a whispered confidence.',
    price: 2990,
    category: 'skincare',
    subcategory: 'eye-care',
    imageUrl: sk(3),
    images: [sk(3), sk(4)],
    ingredients: 'Aqua, Caffeine, Ashwagandha Extract, Hyaluronic Acid, Peptide Complex, Vitamin K, Niacinamide, Glycerin, Cucumber Extract, Natural Fragrance',
    sustainabilityInfo: 'Ashwagandha from certified Madhya Pradesh organic farms. Recyclable aluminium tube. 86% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Rose Quartz Glow Mask',
    slug: 'rose-quartz-glow-mask',
    shortDescription: 'Rose quartz & kaolin clay radiance-restoring mask',
    description: 'Rose quartz — the crystal of love and light — is ground to a fine powder and suspended in this radiance-restoring clay mask. As kaolin draws out impurities with quiet, patient persistence, rose quartz minerals and vitamin C work to reveal the luminous skin that has always resided beneath the surface.',
    price: 2290,
    category: 'skincare',
    subcategory: 'masks',
    imageUrl: sk(4),
    images: [sk(4), sk(0)],
    ingredients: 'Rose Quartz Powder, Kaolin Clay, Vitamin C, Rose Hip Oil, Glycerin, Hyaluronic Acid, Rose Extract, Aloe Vera, Natural Fragrance',
    sustainabilityInfo: 'Rose quartz ethically sourced from certified Indian mines. Refillable glass jar. 94% natural origin. Vegan.',
    isBestseller: false,
    isNew: true,
  },
  {
    name: 'Retinol Night Repair Cream',
    slug: 'retinol-night-repair-cream',
    shortDescription: 'Encapsulated retinol & ceramide restorative night cream',
    description: 'While you sleep, your skin enters its most productive hours. This advanced night cream delivers microencapsulated retinol — released gradually throughout the night for maximum efficacy with minimum sensitivity — alongside ceramides that fortify the skin\'s barrier as it repairs. Wake to skin that has done the most extraordinary quiet work.',
    price: 3690,
    category: 'skincare',
    subcategory: 'moisturisers',
    imageUrl: sk(0),
    images: [sk(0), sk(1)],
    ingredients: 'Aqua, Encapsulated Retinol (0.3%), Ceramide Complex, Hyaluronic Acid, Niacinamide, Peptide Complex, Squalane, Glycerin, Natural Fragrance',
    sustainabilityInfo: 'Encapsulation technology reduces retinol usage by 60% while increasing efficacy. Refillable glass jar. 78% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Vitamin C Radiance Drops',
    slug: 'vitamin-c-radiance-drops',
    shortDescription: '20% stabilised Vitamin C & ferulic acid brightening drops',
    description: 'Vitamin C — the most studied brightening ingredient in modern dermatology — is notoriously unstable. We have solved this with a proprietary stabilisation system that maintains full 20% potency from the first drop to the last. Add three drops to your morning moisturiser and watch the world notice you differently.',
    price: 3290,
    category: 'skincare',
    subcategory: 'serums',
    imageUrl: sk(1),
    images: [sk(1), sk(2)],
    ingredients: 'Ascorbic Acid (Vitamin C, 20%), Ferulic Acid, Vitamin E, Hyaluronic Acid, Propanediol (plant-derived), Aqua, Glutathione',
    sustainabilityInfo: 'Amber glass bottle prevents oxidation, extending product life by 300%. Recyclable. 76% natural origin.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Hyaluronic Aqua Serum',
    slug: 'hyaluronic-aqua-serum',
    shortDescription: 'Triple-weight hyaluronic acid deep hydration serum',
    description: 'Three molecular weights of hyaluronic acid — each penetrating to a different depth within the skin — create a cascade of hydration from the surface to the deepest layers. The result is skin so plump with moisture it seems to generate its own light. This is hydration as architecture.',
    price: 2890,
    category: 'skincare',
    subcategory: 'serums',
    imageUrl: sk(2),
    images: [sk(2), sk(3)],
    ingredients: 'Aqua, Sodium Hyaluronate (High MW), Sodium Hyaluronate (Low MW), Hydrolysed Hyaluronic Acid, Glycerin, Aloe Vera, Panthenol, Centella Asiatica',
    sustainabilityInfo: 'Biofermented hyaluronic acid — vegan, no animal-derived material. Refillable glass dropper. 88% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Saffron Illuminating Toner',
    slug: 'saffron-illuminating-toner',
    shortDescription: 'Kashmiri saffron & rose water brightening essence toner',
    description: 'In the ancient beauty traditions of the subcontinent, saffron was the first step — the morning offering to the skin before all else. This illuminating toner honours that tradition while delivering hyaluronic acid and niacinamide for modern efficacy: a bridge between centuries, applied with a cotton pad.',
    price: 1890,
    category: 'skincare',
    subcategory: 'toners',
    imageUrl: sk(3),
    images: [sk(3), sk(4)],
    ingredients: 'Rose Water, Kashmiri Saffron Extract, Niacinamide, Hyaluronic Acid, Glycerin, Witch Hazel (alcohol-free), Aloe Vera, Natural Fragrance',
    sustainabilityInfo: 'Saffron from Kashmir Saffron GI-certified cooperative. Recycled glass bottle. 93% natural origin. Vegan.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Charcoal Purifying Mask',
    slug: 'charcoal-purifying-mask',
    shortDescription: 'Activated charcoal & bentonite deep pore clarifying mask',
    description: 'Charcoal — activated to a surface area of 1,500 square metres per gram — draws impurities from pores with a magnetic insistence that nothing else can replicate. Combined with bentonite clay and neem extract from the ancient pharmacopoeia, this mask is the weekly reset your skin requires.',
    price: 2090,
    category: 'skincare',
    subcategory: 'masks',
    imageUrl: sk(4),
    images: [sk(4), sk(0)],
    ingredients: 'Activated Charcoal, Bentonite Clay, Neem Extract, Tea Tree Oil, Kaolin, Glycerin, Aloe Vera, Zinc PCA',
    sustainabilityInfo: 'Activated charcoal from sustainable coconut shells. Compostable packaging. 96% natural origin. Vegan.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Bakuchiol Youth Elixir',
    slug: 'bakuchiol-youth-elixir',
    shortDescription: 'Bakuchiol & sea buckthorn plant-powered retinol alternative',
    description: 'Bakuchiol — extracted from the seeds of the babchi plant, used in Ayurveda for centuries — delivers all the age-defying power of retinol without the sensitivity, the peeling, the sun-avoidance. This is the elixir for those who want results without drama: the quiet confidence of natural science.',
    price: 4490,
    category: 'skincare',
    subcategory: 'serums',
    imageUrl: sk(0),
    images: [sk(0), sk(1)],
    ingredients: 'Bakuchiol (Psoralea corylifolia), Sea Buckthorn Oil, Squalane, Hyaluronic Acid, Vitamin E, Peptide Complex, Rosehip Oil, Natural Fragrance',
    sustainabilityInfo: 'Bakuchiol from certified biodynamic Indian farm. 100% vegan retinol alternative. Refillable amber glass. 95% natural origin.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Rose Hip Regenerating Oil',
    slug: 'rose-hip-regenerating-oil',
    shortDescription: 'Pure cold-pressed rosehip & sea buckthorn regenerating face oil',
    description: 'Retinol\'s purest ancestor grows wild in the hedgerows of Chile. Cold-pressed rosehip seed oil — with its extraordinary natural concentration of trans-retinoic acid — works in concert with sea buckthorn\'s vivid antioxidant wealth to regenerate, repair and restore the skin\'s youthful architecture.',
    price: 3190,
    category: 'skincare',
    subcategory: 'face-oils',
    imageUrl: sk(1),
    images: [sk(1), sk(2)],
    ingredients: 'Rosa Canina Seed Oil (100% cold-pressed), Hippophae rhamnoides (Sea Buckthorn) Extract, Vitamin E, Lavender Essential Oil, Chamomile Extract',
    sustainabilityInfo: '100% wild-harvested rosehip from Chile. Single-ingredient transparency. 100% natural origin. Vegan & cruelty-free.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Niacinamide Clarity Serum',
    slug: 'niacinamide-clarity-serum',
    shortDescription: '12% niacinamide & zinc pore-minimising clarity serum',
    description: 'Niacinamide — Vitamin B3 in its most refined form — at 12% concentration is a study in disciplined efficacy: minimising pores, regulating sebum, fading hyperpigmentation, strengthening barrier. Combined with zinc PCA, this serum is clarity distilled into a dropper.',
    price: 2690,
    category: 'skincare',
    subcategory: 'serums',
    imageUrl: sk(2),
    images: [sk(2), sk(3)],
    ingredients: 'Aqua, Niacinamide (12%), Zinc PCA (2%), Hyaluronic Acid, Glycerin, Panthenol, Alpha Arbutin, Tranexamic Acid',
    sustainabilityInfo: 'Niacinamide produced via green chemistry. Minimal packaging philosophy. Refillable glass. 85% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Gold Infused Face Mist',
    slug: 'gold-infused-face-mist',
    shortDescription: '24K gold & rose water instant radiance setting mist',
    description: 'A single press of the atomiser and you are misted in a cloud of rose water and suspended 24K gold — the most extravagant way to set your makeup, refresh mid-afternoon, or simply gift your face a moment of cool, golden luxury. Beauty as theatre.',
    price: 1990,
    category: 'skincare',
    subcategory: 'mists',
    imageUrl: sk(3),
    images: [sk(3), sk(4)],
    ingredients: 'Rose Water, 24K Gold, Hyaluronic Acid, Glycerin, Aloe Vera, Niacinamide, Natural Fragrance',
    sustainabilityInfo: 'Ethically sourced gold. Recycled aluminium mister bottle. 91% natural origin. Vegan.',
    isBestseller: false,
    isNew: true,
  },
  {
    name: 'Jasmine Micellar Water',
    slug: 'jasmine-micellar-water',
    shortDescription: 'Jasmine-infused gentle micellar cleansing water',
    description: 'Micelles — tiny spherical molecules with oil-loving interiors and water-loving surfaces — capture every trace of makeup, pollution and the day\'s residue in a single sweep of a cotton pad. Here, they move through a jasmine-infused water that leaves the skin not merely clean, but softly scented and perfectly balanced.',
    price: 1690,
    category: 'skincare',
    subcategory: 'cleansers',
    imageUrl: sk(4),
    images: [sk(4), sk(0)],
    ingredients: 'Aqua, Poloxamer 184, Jasmine Sambac Extract, Glycerin, Aloe Vera, Chamomile Extract, Panthenol, Allantoin',
    sustainabilityInfo: '100% natural jasmine extract. Zero-rinse formula conserves water. Recycled glass bottle. 89% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'AHA Glow Peel Pads',
    slug: 'aha-glow-peel-pads',
    shortDescription: '10% AHA & willow bark exfoliating glow peel pads',
    description: 'Exfoliation as ritual, not intervention. These pre-saturated pads carry a 10% AHA complex — glycolic and lactic acids working in graduated harmony — alongside willow bark\'s natural salicylates for a complete resurfacing experience that reveals brighter, smoother skin by morning.',
    price: 2890,
    category: 'skincare',
    subcategory: 'treatments',
    imageUrl: sk(0),
    images: [sk(0), sk(1)],
    ingredients: 'Glycolic Acid, Lactic Acid, Willow Bark Extract, Hyaluronic Acid, Aloe Vera, Allantoin, Niacinamide, Panthenol',
    sustainabilityInfo: 'Pads made from 100% organic cotton. Recyclable glass jar. Cruelty-free. 80% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Peptide Firming Cream',
    slug: 'peptide-firming-cream',
    shortDescription: 'Hexapeptide-10 & plant collagen firming day cream',
    description: 'Peptides are the skin\'s own language — short chains of amino acids that signal collagen production, elastin synthesis, cellular renewal. This firming cream speaks that language fluently, with hexapeptide-10 and plant-derived collagen delivering the lifted, tightened contours of skin that has remembered its own youth.',
    price: 3890,
    category: 'skincare',
    subcategory: 'moisturisers',
    imageUrl: sk(1),
    images: [sk(1), sk(2)],
    ingredients: 'Aqua, Hexapeptide-10, Plant Collagen (Wheat-derived), Hyaluronic Acid, Ceramide Complex, Niacinamide, Squalane, Glycerin, Natural Fragrance',
    sustainabilityInfo: 'Plant collagen — no animal-derived ingredients. Refillable luxury glass jar. 83% natural origin.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Centella Soothing Gel',
    slug: 'centella-soothing-gel',
    shortDescription: 'Centella asiatica & aloe vera calming barrier gel',
    description: 'Centella asiatica — called gotu kola in Indian tradition, tiger grass in Korean — has been prescribed by Ayurvedic physicians for wound healing and skin repair for over three thousand years. This cooling gel is the immediate answer to sensitive, reactive, overwrought skin: calm, made tangible.',
    price: 2290,
    category: 'skincare',
    subcategory: 'treatments',
    imageUrl: sk(2),
    images: [sk(2), sk(3)],
    ingredients: 'Centella Asiatica Extract (10%), Aloe Vera (50%), Niacinamide, Hyaluronic Acid, Panthenol, Allantoin, Glycerin, Green Tea Extract',
    sustainabilityInfo: 'Centella grown on certified organic Indian farms. Minimal, recyclable packaging. 95% natural origin. Vegan.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'SPF 50 Glow Shield',
    slug: 'spf-50-glow-shield',
    shortDescription: 'SPF 50 PA++++ mineral sunscreen with luminising finish',
    description: 'The final act of every morning ritual is protection. This mineral-filter sunscreen — SPF 50, PA++++ — is invisible on all skin tones, non-whitening, and leaves a luminous finish that enhances rather than obscures. Sun protection has never asked so little and given so much.',
    price: 2490,
    category: 'skincare',
    subcategory: 'spf',
    imageUrl: sk(3),
    images: [sk(3), sk(4)],
    ingredients: 'Zinc Oxide (20%), Titanium Dioxide (5%), Hyaluronic Acid, Niacinamide, Vitamin C, Mica (luminising), Squalane, Glycerin',
    sustainabilityInfo: 'Reef-safe mineral filters only. No chemical UV absorbers. Recyclable packaging. 88% natural origin. Vegan.',
    isBestseller: true,
    isNew: true,
  },
  {
    name: 'Lip Ritual Nourishing Balm',
    slug: 'lip-ritual-nourishing-balm',
    shortDescription: 'Rose & shea deeply nourishing lip treatment balm',
    description: 'The lips speak, smile, whisper, sing. They deserve their own ritual. This concentrated lip balm — rich with shea, beeswax and rose extract — addresses dryness with an almost maternal tenderness, sealing in moisture while delivering a subtle, natural flush of rose pink.',
    price: 890,
    category: 'skincare',
    subcategory: 'lip-care',
    imageUrl: sk(4),
    images: [sk(4), sk(0)],
    ingredients: 'Shea Butter, Beeswax, Rose Extract, Vitamin E, Coconut Oil, Jojoba Oil, Rose Hip Oil, Natural Fragrance',
    sustainabilityInfo: 'Beeswax from certified ethical UK apiaries. Recyclable aluminium tin. 99% natural origin.',
    isBestseller: false,
    isNew: false,
  },

  // HOME FRAGRANCE (15)
  {
    name: 'Oud & Sandalwood Candle',
    slug: 'oud-sandalwood-candle',
    shortDescription: 'Arabian oud & Mysore sandalwood luxury soy candle',
    description: 'Oud — the resinous heartwood of the agarwood tree, among the rarest and most coveted materials in perfumery — meets the creamy, meditative warmth of Mysore sandalwood in this luxury soy candle. Light it as the sun sets. Let its smoke curl upward like a prayer.',
    price: 2890,
    category: 'home-fragrance',
    subcategory: 'candles',
    imageUrl: hf(0),
    images: [hf(0), hf(1)],
    ingredients: 'Coconut Soy Wax Blend, Cotton Wick (lead-free), Oud Essential Oil, Sandalwood Essential Oil, Natural Fragrance Complex',
    sustainabilityInfo: 'Coconut soy wax — clean burning, no paraffin. Cotton wick, lead-free. Recyclable glass vessel. Hand-poured in small batches. Vegan.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'White Lotus Reed Diffuser',
    slug: 'white-lotus-reed-diffuser',
    shortDescription: 'Sacred white lotus & aquatic reed room diffuser',
    description: 'Still water, white petals, the faintest aquatic breath of morning. This reed diffuser, crafted with sacred white lotus and a signature aquatic accord, transforms any room into a place of serene intention — a constant, gentle meditation that requires nothing of you except presence.',
    price: 3490,
    category: 'home-fragrance',
    subcategory: 'diffusers',
    imageUrl: hf(1),
    images: [hf(1), hf(2)],
    ingredients: 'Dipropylene Glycol (plant-derived), White Lotus Extract, Natural Reed Reeds, Aquatic Accord, Natural Fragrance Complex',
    sustainabilityInfo: 'Plant-derived carrier. Rattan reeds from sustainable Indonesian farms. Refillable glass bottle available. Alcohol-free formula.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Jasmine & Rose Room Spray',
    slug: 'jasmine-rose-room-spray',
    shortDescription: 'Night jasmine & Bulgarian rose instant room fragrance',
    description: 'Four spritzes and your room is transformed: the heavy, honeyed sweetness of night-blooming jasmine lifting above a bed of Bulgarian rose. A room fragrance this intimate is not merely decorative — it is the invisible architecture of how a space makes you feel.',
    price: 1690,
    category: 'home-fragrance',
    subcategory: 'room-sprays',
    imageUrl: hf(2),
    images: [hf(2), hf(3)],
    ingredients: 'Aqua, Alcohol (sugarcane-derived), Jasmine Sambac Extract, Bulgarian Rose Absolute, Natural Fragrance Complex',
    sustainabilityInfo: 'Sugarcane alcohol — carbon-negative. Recycled aluminium bottle. 100% natural fragrance blend. Vegan.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Ancient Forest Candle',
    slug: 'ancient-forest-candle',
    shortDescription: 'Cedar, pine resin & dark moss forest soy candle',
    description: 'Close your eyes. You are standing in an ancient forest at the edge of dusk — the air thick with cedar sap, pine resin, dark wet moss beneath your feet. This candle recreates that primal sense memory with startling fidelity. Some spaces need no adornment beyond the right fragrance.',
    price: 2690,
    category: 'home-fragrance',
    subcategory: 'candles',
    imageUrl: hf(3),
    images: [hf(3), hf(4)],
    ingredients: 'Coconut Soy Wax Blend, Cedar Essential Oil, Pine Resin Absolute, Oakmoss Accord, Natural Fragrance Complex, Cotton Wick',
    sustainabilityInfo: 'Sustainably sourced cedarwood from FSC-certified forests. Soy wax from non-GMO US crops. Recyclable vessel. Hand-poured.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Ritual Incense Sticks',
    slug: 'ritual-incense-sticks',
    shortDescription: 'Sandalwood & frankincense traditional hand-rolled incense',
    description: 'Hand-rolled on bamboo by artisans in Mysore using a craft unchanged for centuries, these incense sticks carry the ancient trinity of sandalwood, frankincense and a trace of rose — the fragrant vocabulary of every sacred space in human history. Twenty sticks, twenty small ceremonies.',
    price: 890,
    category: 'home-fragrance',
    subcategory: 'incense',
    imageUrl: hf(4),
    images: [hf(4), hf(0)],
    ingredients: 'Sandalwood Powder, Frankincense Resin, Rose Extract, Natural Binder (halmaddi), Bamboo Core',
    sustainabilityInfo: 'Hand-rolled by Mysore artisan cooperative — fair wages certified. Zero synthetic fragrance. Bamboo from certified sustainable farms.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Amber & Benzoin Candle',
    slug: 'amber-benzoin-candle',
    shortDescription: 'Warm amber resin & vanilla benzoin cocooning soy candle',
    description: 'Benzoin — a resin tapped from the Styrax tree across South-East Asia — has the uncanny warmth of vanilla without its sweetness: it is comfort without sentimentality. Merged with amber and a thread of labdanum, this candle creates the olfactory sensation of being held.',
    price: 2890,
    category: 'home-fragrance',
    subcategory: 'candles',
    imageUrl: hf(0),
    images: [hf(0), hf(1)],
    ingredients: 'Coconut Soy Wax, Benzoin Absolute, Amber Resin, Labdanum Extract, Natural Fragrance Complex, Cotton Wick',
    sustainabilityInfo: 'Benzoin from ethical Laotian tapping cooperatives. Clean-burning soy wax. Refillable glass vessel program available.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Sacred Space Diffuser Oil',
    slug: 'sacred-space-diffuser-oil',
    shortDescription: 'Palo santo & white sage ultrasonic diffuser oil blend',
    description: 'Across cultures and centuries, palo santo and white sage have been burned to purify space and settle the mind. This ultrasonic diffuser oil carries that sacred intention into a clean, modern format — add ten drops to your diffuser and let your space become what it is meant to be.',
    price: 2290,
    category: 'home-fragrance',
    subcategory: 'diffuser-oils',
    imageUrl: hf(1),
    images: [hf(1), hf(2)],
    ingredients: 'Fractionated Coconut Oil, Palo Santo Essential Oil, White Sage Essential Oil, Frankincense Essential Oil, Cedarwood Essential Oil',
    sustainabilityInfo: 'Palo santo sustainably wild-harvested in Ecuador. White sage from certified California organic farms. 100% essential oil blend. Vegan.',
    isBestseller: false,
    isNew: true,
  },
  {
    name: 'Moonlight Ritual Candle',
    slug: 'moonlight-ritual-candle',
    shortDescription: 'Lunar jasmine, orris & white musk evening soy candle',
    description: 'Some candles belong to mornings, some to afternoons. The Moonlight Ritual Candle belongs entirely to the hour after midnight — to jasmine at its most intoxicating, iris powder at its most powdery-cold, white musk creating an impression of clean skin warmed by sleep.',
    price: 3190,
    category: 'home-fragrance',
    subcategory: 'candles',
    imageUrl: hf(2),
    images: [hf(2), hf(3)],
    ingredients: 'Coconut Soy Wax, Jasmine Absolute, Orris Root Butter, White Musk, Heliotrope Accord, Natural Fragrance Complex, Cotton Wick',
    sustainabilityInfo: 'Jasmine from night-harvest Tamil Nadu cooperative. Orris from certified Florentine organic farm. Recyclable mercury glass vessel.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Neroli & Bergamot Room Spray',
    slug: 'neroli-bergamot-room-spray',
    shortDescription: 'Sicilian neroli & Calabrian bergamot morning room mist',
    description: 'The Italian morning — sunlight on warm stone, citrus groves breathing in the heat, the air sharp and sweet and full of possibility. This room spray captures that hour in a single spritz: neroli and bergamot in their sun-drenched, unsentimental, irreplaceable brightness.',
    price: 1890,
    category: 'home-fragrance',
    subcategory: 'room-sprays',
    imageUrl: hf(3),
    images: [hf(3), hf(4)],
    ingredients: 'Aqua, Alcohol (sugarcane-derived), Neroli Essential Oil, Bergamot Essential Oil, Petitgrain Bigarade, Natural Fragrance Complex',
    sustainabilityInfo: 'Neroli from certified Sicilian organic groves. Bergamot from Reggio Calabria cooperative. Recycled aluminium. 100% natural fragrance.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Ritual of Hammam Candle',
    slug: 'ritual-of-hammam-candle',
    shortDescription: 'Black soap, eucalyptus & cedar hammam soy candle',
    description: 'The hammam is the oldest spa in the world — a place of steam and silence, of black soap and cedar, of the body restored to itself. This candle recreates its aromatic atmosphere: eucalyptus clarity above the deep, smoky cedar, with the soft warmth of olive-oil soap threading through everything.',
    price: 2690,
    category: 'home-fragrance',
    subcategory: 'candles',
    imageUrl: hf(4),
    images: [hf(4), hf(0)],
    ingredients: 'Coconut Soy Wax, Eucalyptus Essential Oil, Cedar Essential Oil, Olive Accord, Black Soap Note, Natural Fragrance Complex, Cotton Wick',
    sustainabilityInfo: 'Clean-burning coconut soy wax. Eucalyptus from certified Australian sustainable farms. Recyclable glass. Hand-poured.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Palo Santo & Cedar Incense',
    slug: 'palo-santo-cedar-incense',
    shortDescription: 'Wild palo santo & Atlas cedar hand-rolled meditation incense',
    description: 'Palo santo — holy wood — has guided meditation rituals across South America for centuries. Its smoke is warm, woody, slightly sweet, and carries with it a quality of mental quietude that is difficult to explain and impossible to forget. Paired with Atlas cedar, it creates a space for the mind to settle.',
    price: 1290,
    category: 'home-fragrance',
    subcategory: 'incense',
    imageUrl: hf(0),
    images: [hf(0), hf(1)],
    ingredients: 'Palo Santo Wood Powder, Atlas Cedarwood, Natural Binder, Bamboo Core',
    sustainabilityInfo: 'Palo santo from sustainably wild-harvested Ecuadorian forests — only fallen trees used. Zero synthetic additives.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Gold Ritual Diffuser',
    slug: 'gold-ritual-diffuser',
    shortDescription: 'Oud, amber & 24K gold luxury statement reed diffuser',
    description: 'An object as much as a fragrance. This statement diffuser — in hand-blown amber glass with 24K gold-dipped reeds — fills a room with the most opulent accord we have ever created: oud resin above amber, labdanum, a thread of rose absolute. It is permanence made fragrant.',
    price: 4890,
    category: 'home-fragrance',
    subcategory: 'diffusers',
    imageUrl: hf(1),
    images: [hf(1), hf(2)],
    ingredients: 'Dipropylene Glycol (plant-derived), Oud Resin Absolute, Amber Complex, Labdanum Extract, Rose Absolute, 24K Gold-Dipped Reed Sticks',
    sustainabilityInfo: 'Hand-blown recycled glass vessel. 24K gold ethically sourced. Refillable cartridge program. Premium artisan production.',
    isBestseller: true,
    isNew: false,
  },
  {
    name: 'Rose & Oud Candle',
    slug: 'rose-oud-candle',
    shortDescription: 'Bulgarian rose absolute & agarwood oud prestige soy candle',
    description: 'The two most precious raw materials in perfumery, sharing one vessel. Bulgarian rose — queen of flowers, costing more by weight than gold — meets agarwood oud in an accord of extraordinary complexity and beauty. This candle is an extravagance. It is also completely worth it.',
    price: 3290,
    category: 'home-fragrance',
    subcategory: 'candles',
    imageUrl: hf(2),
    images: [hf(2), hf(3)],
    ingredients: 'Coconut Soy Wax, Bulgarian Rose Absolute, Agarwood (Oud) Oil, Patchouli, Labdanum, Natural Fragrance Complex, Cotton Wick',
    sustainabilityInfo: 'Bulgarian rose from certified Kazanlak Valley cooperative. Sustainable agarwood from CITES-certified sources. Hand-poured. Recyclable vessel.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Morning Meditation Spray',
    slug: 'morning-meditation-spray',
    shortDescription: 'Citrus, green tea & yuzu awakening morning room mist',
    description: 'Before the day makes its demands, this room spray extends an invitation: a single breath of yuzu, green tea and fresh citrus to locate yourself in the present. Two spritzes into the air above you, eyes closed. The morning begins again, and it is yours.',
    price: 1590,
    category: 'home-fragrance',
    subcategory: 'room-sprays',
    imageUrl: hf(3),
    images: [hf(3), hf(4)],
    ingredients: 'Aqua, Alcohol (sugarcane-derived), Yuzu Essential Oil, Green Tea Extract, Bergamot, Lemon Essential Oil, Natural Fragrance Complex',
    sustainabilityInfo: 'Yuzu from certified Japanese organic farms. Recycled aluminium bottle. 100% natural fragrance. Carbon-neutral shipping.',
    isBestseller: false,
    isNew: false,
  },
  {
    name: 'Midnight Bloom Wax Melts',
    slug: 'midnight-bloom-wax-melts',
    shortDescription: 'Night-blooming jasmine & tuberose soy wax melts',
    description: 'For those evenings when a candle is not enough — when you want fragrance to fill every corner of the room, to saturate the air with something dense and beautiful. These wax melts, in an accord of night-blooming jasmine and tuberose, are extravagance for the senses.',
    price: 1190,
    category: 'home-fragrance',
    subcategory: 'wax-melts',
    imageUrl: hf(4),
    images: [hf(4), hf(0)],
    ingredients: 'Coconut Soy Wax, Jasmine Sambac Absolute, Tuberose Absolute, Natural Fragrance Complex',
    sustainabilityInfo: 'Clean-burning coconut soy wax — no paraffin, no petroleum. Compostable clamshell packaging. Vegan.',
    isBestseller: false,
    isNew: false,
  },
]

async function main() {
  console.log('Seeding database with 60 Saumara products...')

  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    })
  }

  console.log(`Successfully seeded ${products.length} products.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
